apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: ldw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: nowgnodeel/config:0.0.1