logging:
  file:
    name: logs/item.log
  level:
    root: info
    org.msa.item: debug
  logback:
    rolling policy:
      max-file-size: 500MB
      max-history: 10

spring:
  config:
    import:
      - classpath:/config/datasource-local.yaml

# Eureka Server 에 자기자신(item-service)을 등록
eureka:
  instance:
    # prefer-ip-address 는 hostname 이 아닌 ip 주소를 이용해서
    # 유레카 서버에 등록할 것인지 여부를 설정.
    # true : ip 주소를 이용해서 등록하겠다는 설정.
    prefer-ip-address: true
  client:
    # register-with-eureka 는 마이크로 서비스를 유레카 서버 레지스트리에 등록 할 것인지 여부.
    # 현재 yaml 은 item-service 임으로 유레카 서버 레지스트리에 등록이 필요함으로 true 로 설정.
    register-with-eureka: true
    fetch-register: true
    # service-url 은 유레카 서버의 url 정보임.
    service-url:
      defaultZone: http://localhost:8761/eureka